// <auto-generated />
using System;
using ChrisMayor.PiWensnAzureNoiseAnalysis.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChrisMayor.PiWensnAzureNoiseAnalysis.Migrations
{
    [DbContext(typeof(NoiseContext))]
    [Migration("20201205144010_InitalMigration")]
    partial class InitalMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ChrisMayor.PiWensnAzureNoiseAnalysis.Entities.NoiseItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .UseIdentityColumn();

                    b.Property<DateTime>("ExecutionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsTestItem")
                        .HasColumnType("bit");

                    b.Property<double>("SoundLevel")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("NoiseItems");
                });
#pragma warning restore 612, 618
        }
    }
}
